### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by sdegutis** [Flynsarmy/atom-open-terminal-here#6]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Users/sdegutis/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/sdegutis/.atom/packages/open-terminal-here/lib/open-terminal-here.coffee:10:9)
```

**Comment by Flynsarmy** [comment]
Fixed in https://github.com/davidhsv/atom-open-terminal-here/commit/690470d688c630d6c50ee229a1a94ffa299934eb ?
